name: 'Pull Request'
on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14, 16, 18]
        typescript:
          ['~4.7.4', '~4.8.3', '~4.9.5', '~5.0.4', '~5.1.6', '~5.2.2', '~5.3.3', '~5.4.2', 'latest']
    name: Node ${{ matrix.node }} / TS ${{ matrix.typescript }}
    steps:
      - name: 'Checkout latest code'
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: npm ci --legacy-peer-deps
      - name: Install TS at correct version
        run: npm i typescript@${{ matrix.typescript }}
      - name: Run type check
        run: npm run v1-check-types
      - name: Run tests
        run: npm run v1-test

  check_types:
    name: 'Check types'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm ci --legacy-peer-deps
      - name: Check types (v1)
        run: npm run v1-check-types

  lint:
    name: 'ESLint'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm ci --legacy-peer-deps
      - name: Run ESLint
        run: npm run lint

  # prettier:
  #   name: 'Prettier'
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout latest code
  #       uses: actions/checkout@v3
  #       with:
  #         ref: ${{ github.event.pull_request.head.sha }}
  #     - name: Set up node
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: '16'
  #     - name: Install dependencies
  #       run: npm ci --legacy-peer-deps
  #     - name: Run Prettier
  #       run: npm run prettier
